[package]
name = "fmgf"
version = "0.1.0"
authors = ["yossy nakata"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
